blacklist: []
build_space: ../../../build/deps
catkin_make_args: []
cmake_args:
- -DCMAKE_BUILD_TYPE=RelWithDebInfo
devel_layout: linked
devel_space: ../../../devel/deps
extend_path: null
install: false
install_space: ../../../install/deps
isolate_install: false
jobs_args: []
log_space: ../../../logs/deps
make_args: []
source_space: .
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
