##### default.yaml

# general config
config:
  emails: [katarina.cujic@robotics.utias.utoronto.ca]
  docker:
    image: "jenkins/docker_plugin_dep:1.0.2"
    destroy_on_error: false
    destroy_on_job_sucess: false
    destroy_after_days: 5
  slack:
    started: false
    success: false
    failure: false
  message_prefix : default

# Yamlrun file for build to run
yaml: ci/yamlrun/autobuild.yaml

# Stages to run
stages: [build, test]
build:
  timeout: 600
  message: build
  sections: [source, build]
test:
  timeout: 600
  message: test
  sections: [test]
